SELECT	'ALTER TABLE ['+ rtrim(TABLE_NAME)+'] ALTER COLUMN ['+rtrim(COLUMN_NAME)+'] '+rtrim(DATA_TYPE)+
	CASE	WHEN NOT(CHARACTER_MAXIMUM_LENGTH IS NULL) OR (CHARACTER_MAXIMUM_LENGTH=0)
		THEN '('+convert(varchar(10),CHARACTER_MAXIMUM_LENGTH)+')'
	END+
	' COLLATE Cyrillic_General_CI_AS' COLLATE Latin1_General_CI_AS 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE	(TABLE_CATALOG=DB_NAME() COLLATE Cyrillic_General_CI_AS) AND 
		((DATA_TYPE LIKE '%char%' COLLATE Cyrillic_General_CI_AS) OR (DATA_TYPE LIKE '%text%' COLLATE Cyrillic_General_CI_AS)) AND
		(COLLATION_NAME IS NOT NULL) AND
		(COLLATION_NAME <> 'SQL_Latin1_General_CP1251_CI_AS' COLLATE Cyrillic_General_CI_AS) 