ALTER TABLE [UDS] ALTER COLUMN [NAME] nvarchar(MAX) COLLATE Cyrillic_General_CI_AS;
ALTER TABLE [UDS] ALTER COLUMN [UTOCH] nvarchar(MAX) COLLATE Cyrillic_General_CI_AS;
ALTER TABLE [UDS] ALTER COLUMN [NAME_SHORT] nvarchar(MAX) COLLATE Cyrillic_General_CI_AS;
ALTER TABLE [UDS] ALTER COLUMN [TITUL] nvarchar(MAX) COLLATE Cyrillic_General_CI_AS;
ALTER TABLE [UDS] ALTER COLUMN [LAYER] nvarchar(MAX) COLLATE Cyrillic_General_CI_AS;
